# Generated by Django 5.2 on 2025-07-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_encrypted_full_name', models.BinaryField(verbose_name='Nome completo')),
                ('_encrypted_cpf', models.BinaryField(verbose_name='CPF')),
                ('_encrypted_phone', models.BinaryField(editable=True, verbose_name='Telefone')),
                ('_encrypted_email', models.BinaryField(editable=True, verbose_name='E-mail')),
                ('city', models.CharField(max_length=128, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('marital_status', models.CharField(choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viúvo(a)')], max_length=1, verbose_name='Estado Civil')),
                ('birth_date', models.DateField(editable=False, verbose_name='Data de Nascimento')),
                ('employment_status', models.CharField(choices=[('1', 'Funcionário Público'), ('2', 'Assalariado (CLT)'), ('3', 'Autônomo'), ('4', 'Empresário ou PJ'), ('5', 'Profissional Liberal'), ('6', 'Aposentado ou Pensionista'), ('7', 'Desempregado'), ('8', 'Programa Bolsa Família')], max_length=1, verbose_name='Situação Empregatícia')),
                ('privacy_policy', models.BooleanField(editable=False, verbose_name='Política de Privacidade')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data Atualizado')),
                ('cpf_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Hash do CPF')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=128, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Cliente ativo')),
                ('client_since', models.DateTimeField(auto_now_add=True, verbose_name='Cliente Desde')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='LoanProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0001', 'Gerada'), ('0002', 'Enviada para o cliente'), ('0003', 'Aceita'), ('0004', 'Recusada'), ('0005', 'Expirada'), ('0006', 'Cancelada'), ('0007', 'Em conferência'), ('0008', 'Paga na conta do cliente')], max_length=4, verbose_name='Status')),
                ('payment_status', models.CharField(choices=[('0001', 'Em dia'), ('0002', 'Quitado'), ('0003', 'Atrasado'), ('0004', 'Inadimplente')], max_length=4, verbose_name='Status de pagamento')),
                ('released_value', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Valor liberado')),
                ('number_of_installments', models.PositiveSmallIntegerField(editable=False, verbose_name='Quantidade de parcelas')),
                ('value_of_installments', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Valor das parcelas')),
                ('client', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='loan_proposals', to='crm_financeiro.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Proposta de empréstimo',
                'verbose_name_plural': 'Propostas de empréstimo',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveSmallIntegerField(editable=False, verbose_name='Número da parcela')),
                ('due_date', models.DateField(editable=False, verbose_name='Data de vencimento')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Valor')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('loan_proposal', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='crm_financeiro.loanproposal', verbose_name='Proposta de empréstimo')),
            ],
            options={
                'verbose_name': 'Parcelamento',
                'verbose_name_plural': 'Parcelamentos',
            },
        ),
    ]
