# Generated by Django 5.2 on 2025-06-22 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('creditsimulationlead_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='landing_page.creditsimulationlead')),
                ('client_since', models.DateField(auto_now_add=True, verbose_name='Cliente desde')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data atualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Cliente ativo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=('landing_page.creditsimulationlead',),
        ),
        migrations.CreateModel(
            name='LoanProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0001', 'Criada'), ('0002', 'Enviada'), ('0003', 'Aceita'), ('0004', 'Recusada'), ('0005', 'Expirada'), ('0006', 'Cancelada'), ('0007', 'Conferência'), ('0008', 'Enviada para pagamento'), ('0009', 'Paga')], max_length=4, verbose_name='Status')),
                ('payment_status', models.CharField(choices=[('0001', 'Em dia'), ('0002', 'Quitado'), ('0003', 'Atrasado'), ('0004', 'Inadimplente')], max_length=4, verbose_name='Status de pagamento')),
                ('released_value', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Valor liberado')),
                ('number_of_installments', models.PositiveSmallIntegerField(editable=False, verbose_name='Quantidade de parcelas')),
                ('value_of_installments', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Valor das parcelas')),
                ('client', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='loan_proposals', to='crm_financeiro.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Proposta de empréstimo',
                'verbose_name_plural': 'Propostas de empréstimo',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveSmallIntegerField(editable=False, verbose_name='Número da parcela')),
                ('due_date', models.DateField(editable=False, verbose_name='Data de vencimento')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Valor')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('loan_proposal', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='crm_financeiro.loanproposal', verbose_name='Proposta de empréstimo')),
            ],
            options={
                'verbose_name': 'Parcelamento',
                'verbose_name_plural': 'Parcelamentos',
            },
        ),
    ]
