# Generated by Django 5.2 on 2025-07-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True, verbose_name='Slug'),
        ),
    ]
