# Generated by Django 5.2 on 2025-07-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deletion_request_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de solicitação de exclusão'),
        ),
        migrations.AddField(
            model_name='client',
            name='marked_for_deletion',
            field=models.BooleanField(default=False, verbose_name='Marcado para exclusão'),
        ),
    ]
