# Generated by Django 5.2 on 2025-07-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_financeiro', '0002_client_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=256, unique=True, verbose_name='Slug'),
        ),
    ]
