# Generated by Django 5.2.4 on 2025-07-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_financeiro', '0002_client_deletion_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='privacy_policy',
            field=models.BooleanField(verbose_name='Política de Privacidade'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Data Atualizado'),
        ),
    ]
