# Generated by Django 5.2.4 on 2025-07-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_financeiro', '0003_alter_client_birth_date_alter_client_privacy_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='privacy_policy',
            field=models.BooleanField(editable=False, verbose_name='Política de Privacidade'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data Atualizado'),
        ),
    ]
