# Generated by Django 5.2.4 on 2025-07-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_financeiro', '0004_alter_client_privacy_policy_alter_client_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproposal',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=128, unique=True, verbose_name='Slug'),
        ),
    ]
