# Generated by Django 5.2.4 on 2025-07-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_financeiro', '0005_loanproposal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproposal',
            name='status',
            field=models.CharField(choices=[('0001', 'Gerada'), ('0002', 'Enviada para o cliente'), ('0003', 'Aceita'), ('0004', 'Recusada'), ('0005', 'Expirada'), ('0006', 'Cancelada'), ('0008', 'Paga na conta do cliente')], max_length=4, verbose_name='Status'),
        ),
    ]
