# Generated by Django 5.2.4 on 2025-07-26 20:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_financeiro', '0006_alter_loanproposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data Criado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data Atualizado'),
        ),
        migrations.AddField(
            model_name='loanproposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data Criado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanproposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data Atualizado'),
        ),
    ]
