# Generated by Django 5.2.4 on 2025-07-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_financeiro', '0007_installment_created_at_installment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Está cancelado'),
        ),
    ]
