# Generated by Django 5.2.4 on 2025-07-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_financeiro', '0008_installment_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=128, unique=True, verbose_name='Slug'),
        ),
    ]
