# Generated by Django 5.2 on 2025-07-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditSimulationLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_encrypted_full_name', models.BinaryField(verbose_name='Nome completo')),
                ('_encrypted_cpf', models.BinaryField(verbose_name='CPF')),
                ('_encrypted_phone', models.BinaryField(editable=True, verbose_name='Telefone')),
                ('_encrypted_email', models.BinaryField(editable=True, verbose_name='E-mail')),
                ('city', models.CharField(max_length=128, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('marital_status', models.CharField(choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viúvo(a)')], max_length=1, verbose_name='Estado Civil')),
                ('birth_date', models.DateField(editable=False, verbose_name='Data de Nascimento')),
                ('employment_status', models.CharField(choices=[('1', 'Funcionário Público'), ('2', 'Assalariado (CLT)'), ('3', 'Autônomo'), ('4', 'Empresário ou PJ'), ('5', 'Profissional Liberal'), ('6', 'Aposentado ou Pensionista'), ('7', 'Desempregado'), ('8', 'Programa Bolsa Família')], max_length=1, verbose_name='Situação Empregatícia')),
                ('privacy_policy', models.BooleanField(editable=False, verbose_name='Política de Privacidade')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data Atualizado')),
                ('released_value', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Valor liberado')),
                ('number_of_installments', models.PositiveSmallIntegerField(editable=False, verbose_name='Quantidade de parcelas')),
                ('value_of_installments', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Valor das parcelas')),
                ('api_status', models.PositiveSmallIntegerField(editable=False, verbose_name='Status da API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Criado')),
            ],
            options={
                'verbose_name': 'Lead de Simulação de Crédito',
                'verbose_name_plural': 'Leads de Simulação de Crédito',
            },
        ),
    ]
