# Generated by Django 5.2 on 2025-07-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditsimulationlead',
            name='cpf_hash',
            field=models.CharField(editable=False, max_length=64, verbose_name='Hash do CPF'),
        ),
    ]
