# Generated by Django 5.2 on 2025-07-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditsimulationlead',
            name='cpf_hash',
            field=models.CharField(default='s56d4f65ad4s6a5sd46a5sd46a5d4a65sd', editable=False, max_length=64, unique=True, verbose_name='Hash do CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditsimulationlead',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=128, unique=True, verbose_name='Slug'),
        ),
    ]
