# Generated by Django 5.2.4 on 2025-07-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_alter_creditsimulationlead_cpf_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditsimulationlead',
            name='birth_date',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='creditsimulationlead',
            name='privacy_policy',
            field=models.BooleanField(verbose_name='Política de Privacidade'),
        ),
        migrations.AlterField(
            model_name='creditsimulationlead',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Data Atualizado'),
        ),
    ]
