# Generated by Django 5.2.6 on 2025-09-07 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Título')),
                ('short_description', models.CharField(max_length=128, verbose_name='Descrição curta')),
                ('featured_image', models.ImageField(upload_to='blog_posts/', verbose_name='Imagem destacada')),
                ('content', models.TextField(max_length=20000, verbose_name='Conteúdo')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True, verbose_name='Slug')),
                ('views', models.PositiveIntegerField(blank=True, default=0, verbose_name='Visualizações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data Atualizado')),
            ],
            options={
                'verbose_name': 'Postagem do blog',
                'verbose_name_plural': 'Postagens do blog',
            },
        ),
        migrations.CreateModel(
            name='ViewsPerMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(editable=False, verbose_name='Mês')),
                ('total', models.PositiveIntegerField(blank=True, default=0, verbose_name='Total')),
                ('post', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost', verbose_name='Postagem')),
            ],
            options={
                'verbose_name': 'Visualização por mês',
                'verbose_name_plural': 'Visualizações por mês',
                'unique_together': {('post', 'month')},
            },
        ),
    ]
