# Generated by Django 5.2 on 2025-06-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True, verbose_name='Slug'),
        ),
    ]
