# Generated by Django 5.2.5 on 2025-08-28 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='views',
        ),
        migrations.CreateModel(
            name='ViewsPerMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(editable=False, verbose_name='Mês')),
                ('total', models.PositiveIntegerField(blank=True, default=0, verbose_name='Total')),
                ('post', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost', verbose_name='Postagem')),
            ],
            options={
                'unique_together': {('post', 'month')},
            },
        ),
    ]
