# Generated by Django 5.2.5 on 2025-08-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpost_views_viewspermonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Visualizações'),
        ),
    ]
