# Generated by Django 5.2.5 on 2025-08-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewspermonth',
            name='month',
            field=models.DateField(editable=False, unique=True, verbose_name='Mês'),
        ),
    ]
