# Generated by Django 5.2.5 on 2025-08-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_viewspermonth_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewspermonth',
            name='month',
            field=models.DateField(editable=False, verbose_name='Mês'),
        ),
    ]
