# Generated by Django 5.2.5 on 2025-08-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_viewspermonth_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewspermonth',
            options={'verbose_name': 'Visualização por mês', 'verbose_name_plural': 'Visualizações por mês'},
        ),
    ]
